import Sidebar from './components/sections/Sidebar';
// import './globals.css'
import StyledJsxRegistry from './registry';
import { GlobalStyles } from './styles/global'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <StyledJsxRegistry>
          {children}
          <GlobalStyles />
        </StyledJsxRegistry>
      </body>
    </html>
  )
}
